"""Check the A01–A22 / G1–G9 acceptance matrix against gate JUnit results (M13 D10).

Every mapped test must appear exactly once across the given JUnit files and
must have passed (no failure, error or skip). Gate evidence files must exist.
`--render` writes docs/milestones/M13-acceptance.md from the matrix data.
"""

from __future__ import annotations

import argparse
import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
MATRIX = ROOT / "docs/milestones/M13-acceptance.json"
MARKDOWN = ROOT / "docs/milestones/M13-acceptance.md"


def _node(classname: str, name: str) -> str:
    """JUnit classname tests.integration.m05.test_x + name -> m05/test_x.py::name."""
    parts = classname.split(".")
    if parts[:2] == ["tests", "integration"]:
        parts = parts[2:]
    return "/".join(parts) + ".py::" + name.split("[")[0]


def results(junit_files: list[Path]) -> dict[str, list[str]]:
    outcomes: dict[str, list[str]] = {}
    for path in junit_files:
        for case in ET.parse(path).iter("testcase"):
            node = _node(case.get("classname", ""), case.get("name", ""))
            status = "passed"
            for child in case:
                if child.tag in {"failure", "error", "skipped"}:
                    status = child.tag
            outcomes.setdefault(node, []).append(status)
    return outcomes


def check(matrix: dict[str, Any], outcomes: dict[str, list[str]]) -> list[str]:
    problems = []
    rows = {**matrix["scenarios"], **matrix["gates"]}
    for key, row in rows.items():
        if not row["tests"]:
            problems.append(f"{key}: no mapped test")
        for test in row["tests"]:
            seen = outcomes.get(test)
            if not seen:
                problems.append(f"{key}: {test} not executed")
            elif any(status != "passed" for status in seen):
                problems.append(f"{key}: {test} {sorted(set(seen))}")
        for evidence in row.get("evidence", []):
            if not (ROOT / evidence).is_file():
                problems.append(f"{key}: evidence {evidence} missing")
    return problems


def render(matrix: dict[str, Any]) -> str:
    lines = [
        "# M13 acceptance matrix: A01–A22 and G1–G9",
        "",
        "Generated by `scripts/acceptance_matrix.py --render` from",
        "[M13-acceptance.json](M13-acceptance.json). Each row maps a specification scenario",
        "(PROJECT_SPECIFICATION.md §12) or verification gate (MVP_ARCHITECTURE.md §16) to the",
        "integration checks whose passing results in the M13 gate runs prove it. M01–M12",
        "checks run in the development-stack gate (T02); `m13/` checks run against the",
        "reference deployment. `scripts/acceptance_matrix.py --junit …` fails if any mapped",
        "check is missing, skipped or failed.",
        "",
        "| ID | Scenario | Roadmap milestones | Checks |",
        "|---|---|---|---|",
    ]
    for key, row in matrix["scenarios"].items():
        tests = "<br>".join(f"`{t}`" for t in row["tests"])
        lines.append(f"| {key} | {row['title']} | {row['milestones']} | {tests} |")
    lines += ["", "| ID | Gate | Checks | Evidence |", "|---|---|---|---|"]
    for key, row in matrix["gates"].items():
        tests = "<br>".join(f"`{t}`" for t in row["tests"])
        evidence = "<br>".join(f"`{e}`" for e in row.get("evidence", [])) or "—"
        lines.append(f"| {key} | {row['title']} | {tests} | {evidence} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--junit", action="append", type=Path, default=[])
    parser.add_argument("--render", action="store_true")
    parser.add_argument("--report", type=Path)
    args = parser.parse_args()
    matrix = json.loads(MATRIX.read_text())
    if args.render:
        MARKDOWN.write_text(render(matrix))
        print("acceptance matrix: rendered", MARKDOWN.relative_to(ROOT))
    if not args.junit:
        return 0
    outcomes = results(args.junit)
    problems = check(matrix, outcomes)
    summary = {
        "scenarios": len(matrix["scenarios"]),
        "gates": len(matrix["gates"]),
        "mapped_checks": len(
            {t for r in {**matrix["scenarios"], **matrix["gates"]}.values() for t in r["tests"]}
        ),
        "problems": problems,
    }
    if args.report:
        args.report.write_text(json.dumps(summary, indent=2) + "\n")
    for problem in problems:
        print("acceptance-matrix:", problem, file=sys.stderr)
    print(
        f"acceptance matrix: {summary['scenarios']} scenarios, {summary['gates']} gates, "
        f"{summary['mapped_checks']} checks, {len(problems)} problems"
    )
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
