"""Generate docs/api/openapi.json from the implemented routes (M13 D9).

The document is not served by C1 (`openapi_url` stays disabled). Query
parameters come from the boundary allowlist, the only parameters the server
accepts; FastAPI cannot see them because routes parse them explicitly.
`--check` fails when the committed document differs from the implementation.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, cast

from starlette.requests import Request
from starlette.routing import Route

from c1.api.app import _query_allowed, create_app
from c1.config import Settings

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs/api/openapi.json"
_PARAM = re.compile(r"\{([^}:]+)(?::[^}]+)?\}")


def _settings() -> Settings:
    return Settings(
        instance_id="openapi",
        instance_base="urn:c1:instance:openapi:",
        issuer="https://issuer.invalid/realms/c1",
        issuer_alias="c1",
        audience="c1-api",
        fga_url="http://127.0.0.1:1",
        fga_token="unused-placeholder",  # pragma: allowlist secret - never used
        fga_store="unused",
        fga_model="unused",
        terminus_url="http://127.0.0.1:1",
        terminus_password="unused-placeholder",  # pragma: allowlist secret - never used
        organization="admin",
        knowledge_database="unused_k",
        workflow_database="unused_w",
        lock_path=Path("/nonexistent/c1.lock"),
    )


def _version() -> str:
    text = (ROOT / "pyproject.toml").read_text()
    match = re.search(r'^version = "([^"]+)"', text, re.M)
    return match.group(1) if match else "unknown"


def _sample(path: str) -> str:
    return _PARAM.sub("sample", path)


def _flatten(routes: list[Any]) -> list[Route]:
    result: list[Route] = []
    for route in routes:
        inner = getattr(route, "original_router", None)
        if inner is not None:
            result.extend(_flatten(list(inner.routes)))
        elif isinstance(route, Route):
            result.append(route)
    return result


def implemented_routes(app: Any) -> set[tuple[str, str]]:
    """(method, path) of every /v1 route the application really serves."""
    result = set()
    for route in _flatten(list(app.routes)):
        if route.path.startswith("/v1"):
            for method in route.methods or set():
                if method not in {"HEAD", "OPTIONS"}:
                    result.add((method.lower(), _PARAM.sub(r"{\1}", route.path)))
    return result


def documented_routes(document: dict[str, Any]) -> set[tuple[str, str]]:
    return {(m, p) for p, ops in document["paths"].items() for m in ops}


def application() -> Any:
    return create_app(_settings(), runtime=cast(Any, object()))


def build() -> dict[str, Any]:
    app = application()
    document = app.openapi()
    document["info"] = {
        "title": "C1 API",
        "version": _version(),
        "description": (
            "Authenticated C1 HTTP API. Every route except GET /v1/readyz requires an OIDC "
            "bearer access token from the configured issuer. Request bodies are limited to "
            "1 MiB; unknown query parameters, duplicate parameters and backend selectors are "
            "rejected with 400. Errors are RFC 9457 Problem Details. Generated by "
            "scripts/openapi.py; not served by C1."
        ),
    }
    document["components"] = document.get("components", {})
    document["components"]["securitySchemes"] = {
        "bearer": {"type": "http", "scheme": "bearer", "bearerFormat": "JWT"}
    }
    paths: dict[str, Any] = {}
    for path, operations in sorted(document.get("paths", {}).items()):
        clean = _PARAM.sub(r"{\1}", path)
        for method, operation in operations.items():
            scope = {
                "type": "http",
                "method": method.upper(),
                "path": _sample(clean),
                "headers": [],
                "query_string": b"",
            }
            allowed = sorted(_query_allowed(Request(scope)))
            params = [p for p in operation.get("parameters", []) if p.get("in") != "query"]
            for name in allowed:
                params.append(
                    {"name": name, "in": "query", "required": False, "schema": {"type": "string"}}
                )
            if params:
                operation["parameters"] = params
            if not (method == "get" and clean == "/v1/readyz"):
                operation["security"] = [{"bearer": []}]
            operation.setdefault("responses", {})
            for code, text in (
                ("400", "Invalid request"),
                ("401", "Missing or invalid bearer token"),
                ("404", "Not found, or not available to the caller"),
                ("503", "Not ready, or a required service is unavailable"),
            ):
                operation["responses"].setdefault(code, {"description": text})
        paths[clean] = operations
    document["paths"] = paths
    return cast(dict[str, Any], document)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = json.dumps(build(), indent=2, sort_keys=True) + "\n"
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text() != rendered:
            print("docs/api/openapi.json is out of date; run scripts/openapi.py", file=sys.stderr)
            return 1
        print("openapi: current")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered)
    print(f"openapi: wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
